name: Deployement Exercise 2
on: push
jobs:
  lint: 
    run-on: ubuntu-latest
    steps: 
      - name: Get Code
        user: action/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: lint
        run: npm run lint
  test:
    run-on: ubuntu-latest
    steps: 
      - name: Get Code
        user: action/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Test Code
        run: npm run test
  deploy:
    run-on: ubuntu-latest
    steps: 
      - name: Get Code
        user: action/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run Build
      - name: Deploy Code
        run: echo "Deplying ..."
